version: '3.5'
services:
  app:
    build:
      context: .
    ports:
      - 3000:3000
    volumes: &volumes
      - .:/app:cached
      - ~/.bash_history:/root/.bash_history
    command: npm start
    stdin_open: true
    tty: true
